services:
  link:
    build: .
    container_name: link
    ports:
      - "2001:4282"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    pids_limit: 50