services:
  intoretlib:
    build: .
    container_name: intoretlib
    ports:
    - 2002:8583
    restart: unless-stopped
    read_only: true
    tmpfs:
      /run/ctf: size=1m,mode=0755
      /tmp: size=16m,mode=1777
    cap_drop:
    - ALL
    security_opt:
    - no-new-privileges:true
    mem_limit: 128m
    pids_limit: 50
<<<<<<< HEAD
    image: cybreak/intoretlib:instancer-v1
=======
    image: cybreak/intoretlib:latest
>>>>>>> db7fd10ed33b83e07d6cf930eaf9616df1fecafb
    environment:
      RCTF_FLAG: CYB26{local_testing_flag}
    cap_add:
    - CHOWN
    - SETUID
    - SETGID
