services:
  viewer-chall:
    build: .
    restart: unless-stopped
    environment:
    - TERM=xterm
    - RCTF_FLAG=CYB26{local_testing_flag}
    ulimits:
      nproc: 65535
      core: 0
    ports:
    - 4001:1337
<<<<<<< HEAD
    image: cybreak/viewer:instancer-v1
=======
    image: cybreak/viewer:latest
>>>>>>> db7fd10ed33b83e07d6cf930eaf9616df1fecafb
